name: NextPlay - Deploy to Kubernetes

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["NextPlay - Build & Push Docker Images"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy with Kustomize
        run: kubectl apply -k kube/base